[project]
name = "train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "erwan serandour", email = "e.serandour@hispeed.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "anki-scroll",
    "dspy>=3.0.4",
    "ipykernel>=7.1.0",
    "jinja2>=3.1.6",
    "markdown>=3.6",
    "matplotlib>=3.10.7",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
anki-scroll = { workspace = true }
